# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Corral < Formula
  desc "Agent harness and scheduler. Run, schedule, and manage autonomous AI coding agents."
  homepage "https://github.com/Inspirify/corral"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Inspirify/corral/releases/download/v0.1.0/corral_darwin_amd64.tar.gz"
      sha256 "12778d5f49dd940a931807faf65502919180fb401f6d1a961f4100322c1be05a"

      define_method(:install) do
        bin.install "corral"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Inspirify/corral/releases/download/v0.1.0/corral_darwin_arm64.tar.gz"
      sha256 "b5bf6679abac74bf67fdddabeaaeab8c9c8cf7718b4957fe546326e66eac6582"

      define_method(:install) do
        bin.install "corral"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inspirify/corral/releases/download/v0.1.0/corral_linux_amd64.tar.gz"
      sha256 "2980f46e14b52c2922d6a6b51ae4b8534c2bcb619763873d1e695c7dfa3946a3"
      define_method(:install) do
        bin.install "corral"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inspirify/corral/releases/download/v0.1.0/corral_linux_arm64.tar.gz"
      sha256 "8ea3aa3bbcc809aceabf199a64b4baf7a14924c030a45ef2e72f14f9b864a47f"
      define_method(:install) do
        bin.install "corral"
      end
    end
  end

  test do
    system "#{bin}/corral", "version"
  end
end
