# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CorralAgent < Formula
  desc "Agent harness and scheduler. Run, schedule, and manage autonomous AI coding agents."
  homepage "https://github.com/Inspirify/corral"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Inspirify/corral/releases/download/v0.1.0/corral_darwin_amd64.tar.gz"
      sha256 "84a5acdb6af046972c80077db2c1536269142484d4f25a3524c48b709b8c8c01"

      define_method(:install) do
        bin.install "corral"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Inspirify/corral/releases/download/v0.1.0/corral_darwin_arm64.tar.gz"
      sha256 "ef501fbf93b5d4f954c5f550be1f47ca9725bd970ad44097f3e63a3271d5ddc8"

      define_method(:install) do
        bin.install "corral"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inspirify/corral/releases/download/v0.1.0/corral_linux_amd64.tar.gz"
      sha256 "d90fd72dcac0a2c648cedbe9ea4c90904ac899008a70f1db65f21ba23d0b37ea"
      define_method(:install) do
        bin.install "corral"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Inspirify/corral/releases/download/v0.1.0/corral_linux_arm64.tar.gz"
      sha256 "d24c8adfc4f26c9d5236babb174359cf139583df2887058f0cf4bb509e6eef64"
      define_method(:install) do
        bin.install "corral"
      end
    end
  end

  conflicts_with "corral"

  test do
    system "#{bin}/corral", "version"
  end
end
